{ config, lib, pkgs, ... }:

with lib;

let
  sysCfg = config.sys;
  cfg = sysCfg.hardware;
in
{
  options.sys.hardware = {
    isX64 = mkEnableOption "options for x86_64 systems" // { default = pkgs.stdenv.isx86_64; };
  };

  config = {
    hardware = {
      cpu.intel.updateMicrocode = cfg.isX64;
      cpu.amd.updateMicrocode = cfg.isX64;
      enableAllFirmware = true;
      opengl = {
        enable = true;
        driSupport = true;
        driSupport32Bit = cfg.isX64;
      };
    };

    # Firmware update service
    services.fwupd.enable = true;
    environment.systemPackages = with pkgs; [
      # Sensors (fans, temp)
      lm_sensors

      # Manually set CPU governor
      # cpupower frequency-set -g powersave
      config.boot.kernelPackages.cpupower
    ];

    # TODO
    # hardware.fancontrol = {
    #   #enable = true;
    #   config = ''
    #     # Configuration file generated by pwmconfig, changes will be lost
    #     INTERVAL=10
    #     DEVPATH=hwmon3=devices/pci0000:00/0000:00:1f.3/i2c-0/0-002f
    #     DEVNAME=hwmon3=w83793
    #     FCTEMPS=hwmon3/device/pwm2=hwmon0/temp2_input
    #     #FCFANS= hwmon3/device/pwm2=hwmon3/device/fan7_input+hwmon3/device/fan6_input+hwmon3/device/fan5_input
    #     FCFANS=hwmon3/device/pwm2=hwmon3/device/fan7_input
    #     MINTEMP=hwmon3/device/pwm2=45
    #     MAXTEMP=hwmon3/device/pwm2=65
    #     MINSTART=hwmon3/device/pwm2=150
    #     MINSTOP=hwmon3/device/pwm2=0
    #   '';
    # };

    # boot.kernelModules = [
    #   "coretemp"
    #   "i5k_amb"
    #   "w83627hf"
    #   "w83793"
    # ];

    # # powerManagement.cpuFreqGovernor = "powersave";
    # # powerManagement.powertop.enable = true;
    # # services.thermald.enable = true;

    # environment.etc."sysconfig/lm_sensors".text = ''
    #   # Generated by sensors-detect on Sun Mar 27 22:49:14 2022
    #   # This file is sourced by /etc/init.d/lm_sensors and defines the modules to
    #   # be loaded/unloaded.
    #   #
    #   # The format of this file is a shell script that simply defines variables:
    #   # HWMON_MODULES for hardware monitoring driver modules, and optionally
    #   # BUS_MODULES for any required bus driver module (for example for I2C or SPI).

    #   HWMON_MODULES="coretemp i5k_amb w83627hf w83793"
    # '';
  };
}
