# TODO: https://www.reddit.com/r/NixOS/comments/6gh32h/suggestions_for_organizing_nixos_configs/
# Search for config options at: https://search.nixos.org/options?channel=21.11
{ config, pkgs, ... }:

{
  # Use the GRUB 2 boot loader.
  #boot.kernelParams = ["nomodeset"];
  boot.kernelParams = [
    #"console=ttyS0"
	  "boot_on_fail"
  ];
  boot.loader.timeout = 1;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.grub = {
    enable = true;
    #efiInstallAsRemovable = true;
    splashImage = null;
    zfsSupport = true;
    efiSupport = true;
    #mirroredBoots = [];  # Complete in host file
  };

  time.timeZone = "America/Los_Angeles";

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.david = {
    isNormalUser = true;
    createHome = true;
    extraGroups = [
      "wheel"
      "docker"
      "audio"
      "video"
    ];
    hashedPassword = "$6$HMrRhU.Z6Rrr5aYX$AUI.Vo0pe7r/JQ3hEBKH69KV8OeddPJS8EC/9YhSOuAgNTKsmX0aoMfdkitCHdeazXuP2eCBEF5IuFgNFeagS0";
    shell = pkgs.fish;
  };

  # List packages installed in system profile. To search, run:
  # $ nix search wget
  nixpkgs.config.allowUnfree = true;
  environment.systemPackages = with pkgs; [
    vim
    curl
    #docker
    fish
    tmux
    #ipmicfg
    #ipmitool
    #ipmiutil
 
    lm_sensors

    #cudatoolkit
    lsof
    
    bottom
    ripgrep

    # lspci -v | grep -iA8 'network\|ethernet'
    pciutils
  ];

  environment.shells = [ pkgs.fish ];

  hardware.fancontrol = {
    #enable = true;
    config = ''
      # Configuration file generated by pwmconfig, changes will be lost
      INTERVAL=10
      DEVPATH=hwmon3=devices/pci0000:00/0000:00:1f.3/i2c-0/0-002f
      DEVNAME=hwmon3=w83793
      FCTEMPS=hwmon3/device/pwm2=hwmon0/temp2_input
      #FCFANS= hwmon3/device/pwm2=hwmon3/device/fan7_input+hwmon3/device/fan6_input+hwmon3/device/fan5_input
      FCFANS=hwmon3/device/pwm2=hwmon3/device/fan7_input
      MINTEMP=hwmon3/device/pwm2=45
      MAXTEMP=hwmon3/device/pwm2=65
      MINSTART=hwmon3/device/pwm2=150
      MINSTOP=hwmon3/device/pwm2=0
    '';
  };

  hardware.cpu.intel.updateMicrocode = true;
  hardware.cpu.amd.updateMicrocode = true;
  hardware.enableAllFirmware = true;
  services.fwupd.enable = true;

  boot.kernelModules = [ 
    "coretemp"
    "i5k_amb"
    "w83627hf"
    "w83793"
  ];

  powerManagement.cpuFreqGovernor = "powersave";
  powerManagement.powertop.enable = true;

  services.thermald.enable = true;
  environment.etc."sysconfig/lm_sensors".text = ''
    # Generated by sensors-detect on Sun Mar 27 22:49:14 2022
    # This file is sourced by /etc/init.d/lm_sensors and defines the modules to
    # be loaded/unloaded.
    #
    # The format of this file is a shell script that simply defines variables:
    # HWMON_MODULES for hardware monitoring driver modules, and optionally
    # BUS_MODULES for any required bus driver module (for example for I2C or SPI).
    
    HWMON_MODULES="coretemp i5k_amb w83627hf w83793"
  '';

  virtualisation = {
    docker = {
      enable = true;
      enableOnBoot = true;
    };
  };

  # System maintenance
  system = {
    #copySystemConfiguration = true;

    # Autoupgrade
    autoUpgrade = {
      enable = true;
      allowReboot = true;
      flake = "github:NixOS/nixpkgs/nixos-21.11-small";
      flags = [ "--update-input" "nixpkgs" "--commit-lock-file" ];
      dates = "Sat, 02:00";
    };
  };

  # Nix store maintenance
  nix = {
    extraOptions = ''
      keep-outputs = true
      keep-derivations = true
    '';

    gc = {
      automatic = true;
      dates = "Sat, 01:00";
      options = "--delete-older-than 14d";
    };
   
    optimise = {
      automatic = true;
      dates = [ "Sat, 03:00" ];
    };
  };

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "21.11"; # Did you read the comment?
}

