# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  swapDevices =
    [{ device = "/dev/disk/by-uuid/38d458a8-e4cf-43e7-9175-999c44159e2e"; }
      { device = "/dev/disk/by-uuid/ff216402-a66b-4b90-be06-c38582a8c34a"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  fileSystems."/" =
    {
      device = "fast/nixos/root";
      fsType = "zfs";
    };

  fileSystems."/boot/efi0" =
    {
      device = "/dev/disk/by-uuid/A408-8BD3";
      fsType = "vfat";
    };

  fileSystems."/fast" =
    {
      device = "fast";
      fsType = "zfs";
    };

  fileSystems."/home/david" =
    {
      device = "fast/home/david";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    {
      device = "fast/nixos/nix";
      fsType = "zfs";
    };

  fileSystems."/root" =
    {
      device = "fast/home/root";
      fsType = "zfs";
    };

  fileSystems."/var/lib/containerd/io.containerd.content.v1.content" =
    {
      device = "fast/containers/containerd/content";
      fsType = "zfs";
    };

  fileSystems."/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs" =
    {
      device = "/dev/disk/by-uuid/87ef142b-9216-4572-8b3f-5f8d0e8d507e";
      fsType = "ext4";
    };

  fileSystems."/var/lib/docker" =
    {
      device = "fast/containers/docker";
      fsType = "zfs";
    };

  fileSystems."/zfs" =
    {
      device = "fast/zfs";
      fsType = "zfs";
    };
}
