# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "mpt3sas" "isci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "fast/nixos/root";
      fsType = "zfs";
    };

  fileSystems."/root" =
    { device = "fast/home/root";
      fsType = "zfs";
    };

  fileSystems."/home/david" =
    { device = "fast/home/david";
      fsType = "zfs";
    };

  fileSystems."/var/lib/containerd/io.containerd.snapshotter.v1.zfs" =
    { device = "fast/containerd";
      fsType = "zfs";
    };

  fileSystems."/boot/efi0" =
    { device = "/dev/disk/by-uuid/D10A-E7FF";
      fsType = "vfat";
    };

  fileSystems."/boot/efi1" =
    { device = "/dev/disk/by-uuid/D007-7D72";
      fsType = "vfat";
    };

  fileSystems."/boot/efi2" =
    { device = "/dev/disk/by-uuid/388C-755D";
      fsType = "vfat";
    };

  fileSystems."/slow/backup/david/archbook-duplicacy" =
    { device = "slow/backup/david/archbook-duplicacy";
      fsType = "zfs";
    };

  fileSystems."/slow/recover/backup/david/nebula-windows" =
    { device = "slow/backup/david/nebula-windows";
      fsType = "zfs";
    };

  fileSystems."/slow/backup/chelsea/windows-laptop" =
    { device = "slow/backup/chelsea/windows-laptop";
      fsType = "zfs";
    };

  fileSystems."/slow/backup/david/mail" =
    { device = "slow/backup/david/mail";
      fsType = "zfs";
    };

  fileSystems."/slow/media/photos" =
    { device = "slow/media/photos";
      fsType = "zfs";
    };

  fileSystems."/slow/media/ebooks" =
    { device = "slow/media/ebooks";
      fsType = "zfs";
    };

  fileSystems."/slow/media/video/movies" =
    { device = "slow/media/video/movies";
      fsType = "zfs";
    };

  fileSystems."/slow/media/audio" =
    { device = "slow/media/audio";
      fsType = "zfs";
    };

  fileSystems."/slow/backup/david/motog5" =
    { device = "slow/backup/david/motog5";
      fsType = "zfs";
    };

  fileSystems."/slow/media/comics" =
    { device = "slow/media/comics";
      fsType = "zfs";
    };

  fileSystems."/slow/media/video/tv" =
    { device = "slow/media/video/tv";
      fsType = "zfs";
    };

  fileSystems."/slow/documents" =
    { device = "slow/documents";
      fsType = "zfs";
    };

  fileSystems."/slow/media/video/isos" =
    { device = "slow/media/video/isos";
      fsType = "zfs";
    };

  fileSystems."/slow/old/games" =
    { device = "slow/games";
      fsType = "zfs";
    };

  fileSystems."/slow/media/video/personal" =
    { device = "slow/media/video/personal";
      fsType = "zfs";
    };

  fileSystems."/slow/media/video/transcode" =
    { device = "slow/media/video/transcode";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2bab50cb-c97d-4e2f-8ffc-0d957b1e7cbf"; }
      { device = "/dev/disk/by-uuid/cfabdcdc-e671-43ee-83d9-c487e5376454"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.flannel.1.useDHCP = lib.mkDefault true;
  # networking.interfaces.mynet.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth235fc857.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth4b5be979.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth56858282.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth57cb93cc.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth6806c05e.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth6eaf1f44.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth73184d89.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth7f063469.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethbdbedb34.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethc77c437a.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethdfd305e1.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethed4eaa17.useDHCP = lib.mkDefault true;

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
