# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  swapDevices = [
    {device = "/dev/disk/by-uuid/5a22e348-4fa6-483c-8fcd-8d41d64583ec";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  #fileSystems."/" = {
  #  device = "fast/nixos/root";
  #  fsType = "zfs";
  #};

  #fileSystems."/boot" = {
  #  device = "/dev/disk/by-uuid/D713-3B93";
  #  fsType = "vfat";
  #};

  #fileSystems."/home/david" = {
  #  device = "fast/home/david";
  #  fsType = "zfs";
  #};

  #fileSystems."/nix" = {
  #  device = "fast/nixos/nix";
  #  fsType = "zfs";
  #};

  #fileSystems."/var/lib/containerd/io.containerd.content.v1.content" = {
  #  device = "fast/containerd/content";
  #  fsType = "zfs";
  #};

  #fileSystems."/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs" = {
  #  device = "fast/containerd/snapshotter";
  #  fsType = "zfs";
  #};

  #fileSystems."/var/lib/docker" = {
  #  device = "fast/docker";
  #  fsType = "zfs";
  #};

  #fileSystems."/zfs" = {
  #  device = "fast/zfs";
  #  fsType = "zfs";
  #};
}
