# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_acpi" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  swapDevices =
    [{ device = "/dev/disk/by-uuid/e1ceee5e-3e28-4c83-bd18-1b0dff945a07"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  fileSystems."/" =
    {
      device = "upool/nixos/root";
      fsType = "zfs";
    };

  fileSystems."/boot/efi" =
    {
      device = "/dev/disk/by-uuid/C9F6-4350";
      fsType = "vfat";
    };

  fileSystems."/home/david" =
    {
      device = "upool/home/david";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    {
      device = "upool/nixos/nix";
      fsType = "zfs";
    };

  fileSystems."/root" =
    {
      device = "upool/home/root";
      fsType = "zfs";
    };

  fileSystems."/upool" =
    {
      device = "upool";
      fsType = "zfs";
    };
}
