# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  swapDevices = [
    {device = "/dev/disk/by-uuid/ff216402-a66b-4b90-be06-c38582a8c34a";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  fileSystems."/" = {
    device = "fast/nixos/root";
    fsType = "zfs";
  };

  fileSystems."/boot/efi0" = {
    device = "/dev/disk/by-uuid/A408-8BD3";
    fsType = "vfat";
  };

  fileSystems."/fast" = {
    device = "fast";
    fsType = "zfs";
  };

  fileSystems."/home/david" = {
    device = "fast/home/david";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "fast/nixos/nix";
    fsType = "zfs";
  };

  fileSystems."/root" = {
    device = "fast/home/root";
    fsType = "zfs";
  };

  fileSystems."/slow" = {
    device = "slow";
    fsType = "zfs";
  };

  fileSystems."/slow/backups/michael" = {
    device = "slow/backups/michael";
    fsType = "zfs";
  };

  fileSystems."/slow/backups/sue" = {
    device = "slow/backups/sue";
    fsType = "zfs";
  };

  fileSystems."/slow/documents/michael" = {
    device = "slow/documents/michael";
    fsType = "zfs";
  };

  fileSystems."/slow/documents/sue" = {
    device = "slow/documents/sue";
    fsType = "zfs";
  };

  fileSystems."/zfs" = {
    device = "fast/zfs";
    fsType = "zfs";
  };
}
